const resObj=[
  
    {
      "id": "101",
      "name": "Gaurav's Pizza Center",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/740a92bd202ffd40813bc354b86005db",
      "locality": "MG Road",
      "areaName": "Central City",
      "costForTwo": "₹500 for two",
      "cuisines": ["Pizza ", "Italian ", "Fast Food"],
      "avgRating": 4.3,
      "totalRatingsString": "12K+",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹100",
      "link": "https://www.swiggy.com/restaurants/dominos"
    },
    {
      "id": "102",
      "name": "Krishna Pure Veg Points",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_264,h_288,c_fill/ee4131fd2ba063b8fe1b815586d1fe83",
      "locality": "Celestial Building",
      "areaName": "Sigra",
      "costForTwo": "₹400 for two",
      "cuisines": ["Burgers ", "Fast Food ", "Rolls & Wraps "],
      "avgRating": 4.4,
      "totalRatingsString": "18K+",
      "sla": { "deliveryTime": 25, "slaString": "20-25 mins" },
      "discount": "50% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹80",
      "link": "https://www.swiggy.com/restaurants/kfc"
    },
    {
      "id": "103",
      "name": "Arpit Maharaja Thali",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/s07lkfu63igaaa8cyzxh",
      "locality": "Phoenix Mall",
      "areaName": "South Zone",
      "costForTwo": "₹350 for two",
      "cuisines": ["Veg Thali ", "Simple Thali ", "Special Thali"],
      "avgRating": 4.5,
      "totalRatingsString": "25K+",
      "sla": { "deliveryTime": 20, "slaString": "15-20 mins" },
      "discount": "30% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/mcdonalds"
    },
    {
      "id": "104",
      "name": "Villu Thalassery Biryani",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/htra1ceo32gospqkqalp",
      "locality": "Infinity Mall",
      "areaName": "West Side",
      "costForTwo": "₹300 for two",
      "cuisines": ["Thala Special ", "China Thala ", "RCB special"],
      "avgRating": 4.2,
      "totalRatingsString": "14K+",
      "sla": { "deliveryTime": 28, "slaString": "25-30 mins" },
      "discount": "20% OFF",
      "deliveryTime": "35",
      "discountSubHeader": "UPTO ₹60",
      "link": "https://www.swiggy.com/restaurants/burger-king"
    },
    {
      "id": "105",
      "name": "Anup Roll Corner",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/FOOD_CATALOG/IMAGES/CMS/2025/2/21/50e8ebb2-c65d-4e08-a26d-12787d952eac_e5bfb1ca-6688-459b-bb35-d29bb03a0945.jpg",
      "locality": "Mall Road",
      "areaName": "North City",
      "costForTwo": "₹450 for two",
      "cuisines": ["Veg Roll ", "Spring Roll", "Japanese Roll"],
      "avgRating": 4.5,
      "totalRatingsString": "10K+",
      "sla": { "deliveryTime": 35, "slaString": "30-35 mins" },
      "discount": "45% OFF",
      "deliveryTime": "21",
      "discountSubHeader": "UPTO ₹120",
      "link": "https://www.swiggy.com/restaurants/pizza-hut"
    },
    {
      "id": "106",
      "name": "Dhruv Da Dhaba",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/10/11/5e389848-3d97-4cc0-b1fe-0348a9fb2105_b733a54f-9bc5-41ec-b796-aa62a57396e0.jpeg",
      "locality": "Connaught Place",
      "areaName": "Central Delhi",
      "costForTwo": "₹250 for two",
      "cuisines": ["Indian, ", "Street Food, ", "Sweets"],
      "avgRating": 4.6,
      "totalRatingsString": "30K+",
      "sla": { "deliveryTime": 18, "slaString": "15-20 mins" },
      "discount": "25% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹50",
      "link": "https://www.swiggy.com/restaurants/haldirams"
    },
    {
      "id": "107",
      "name": "Nitesh Golden Snacks",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/prfmgw6in1hrqryklqar",
      "locality": "Cyber Hub",
      "areaName": "Gurgaon",
      "costForTwo": "₹350 for two",
      "cuisines": ["Healthy Food, ", "Salads, ", "Fast Food, "],
      "avgRating": 4.1,
      "totalRatingsString": "8K+",
      "sla": { "deliveryTime": 22, "slaString": "20-25 mins" },
      "discount": "35% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/subway"
    },
    {
      "id": "108",
      "name": "Anjali - Ice Cream, Shakes & Sundaes",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/tm5qi7scf04d0dypdprr",
      "locality": "Cyber Hub",
      "areaName": "Gurgaon",
      "costForTwo": "₹350 for two",
      "cuisines": ["Healthy Food, ", "Salads, ", "Fast Food, "],
      "avgRating": 4.1,
      "totalRatingsString": "8K+",
      "sla": { "deliveryTime": 22, "slaString": "20-25 mins" },
      "discount": "35% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/subway"
    },
    {
      "id": "108",
      "name": "Mayur Cafe",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/klwpmxazbvc0iaunerfm",
      "locality": "Cyber Hub",
      "areaName": "Gurgaon",
      "costForTwo": "₹350 for two",
      "cuisines": ["Healthy Food, ", "Salads, ", "Fast Food, "],
      "avgRating": 4.1,
      "totalRatingsString": "8K+",
      "sla": { "deliveryTime": 22, "slaString": "20-25 mins" },
      "discount": "35% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/subway"
    },
    {
      "id": "109",
      "name": "Jain Bakers",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/9/6/fdc7b0b2-c625-44da-b779-32a056365c7d_74946b5a-537a-45bb-b74c-f206382a6f46.jpg",
      "locality": "Cyber Hub",
      "areaName": "Gurgaon",
      "costForTwo": "₹350 for two",
      "cuisines": ["Healthy Food, ", "Salads, ", "Fast Food, "],
      "avgRating": 4.1,
      "totalRatingsString": "8K+",
      "sla": { "deliveryTime": 22, "slaString": "20-25 mins" },
      "discount": "35% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/subway"
    },
    {
      "id": "110",
      "name": "Omji Dhosa Corner",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/bd7dc138a69b46d66445074cb9c4e951",
      "locality": "Cyber Hub",
      "areaName": "Gurgaon",
      "costForTwo": "₹350 for two",
      "cuisines": ["Healthy Food, ", "Salads, ", "Fast Food, "],
      "avgRating": 4.1,
      "totalRatingsString": "8K+",
      "sla": { "deliveryTime": 22, "slaString": "20-25 mins" },
      "discount": "35% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/subway"
    },
    {
      "id": "111",
      "name": "Yadav's Lassi",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/1aa2148e2a8abd14b7a21fe239685d5b",
      "locality": "Cyber Hub",
      "areaName": "Gurgaon",
      "costForTwo": "₹350 for two",
      "cuisines": ["Healthy Food, ", "Salads, ", "Fast Food, "],
      "avgRating": 4.1,
      "totalRatingsString": "8K+",
      "sla": { "deliveryTime": 22, "slaString": "20-25 mins" },
      "discount": "35% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/subway"
    },
    {
      "id": "111",
      "name": "Yadav's Lassi",
      "cloudinaryImageId": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/1aa2148e2a8abd14b7a21fe239685d5b",
      "locality": "Cyber Hub",
      "areaName": "Gurgaon",
      "costForTwo": "₹350 for two",
      "cuisines": ["Healthy Food, ", "Salads, ", "Fast Food, "],
      "avgRating": 3.1,
      "totalRatingsString": "8K+",
      "sla": { "deliveryTime": 22, "slaString": "20-25 mins" },
      "discount": "35% OFF",
      "deliveryTime": "25",
      "discountSubHeader": "UPTO ₹90",
      "link": "https://www.swiggy.com/restaurants/subway"
    }
  
];

export default resObj;